

services:
  app:
    build:
      context: ./ 
      dockerfile: Dockerfile
   
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - ../backend:/var/www/html
    networks:
      - cms-network
    ports:                   
      - "8000:8000"

  frontend:
    build:
      context: ../frontend   
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - cms-network

  webserver:
    image: nginx:alpine
    container_name: php_web
    ports:
      - "8081:80"
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      
    networks:
      - cms-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: cms_pass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cms-network

volumes:
  dbdata:

networks:
  cms-network:
